package main

import "fmt"

// Problem 2: Even Fibonacci numbers
// Each new term in the Fibonacci sequence is generated by adding the
// previous two terms. By starting with 1 and 2, the first 10 terms
// will be:
//   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do
// not exceed four million, find the sum of the even-valued terms.
func main() {
	const want = 4613732
	got := 0
	prev, next := 0, 1
	for next < 4000000 {
		prev, next = next, prev+next
		if next%2 == 0 {
			got += next
		}
	}
	fmt.Printf("got:%d == want:%d = %t", got, want, got == want)
}
